# Generated by Django 3.1 on 2020-08-26 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200825_2305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('course', 'user')},
        ),
    ]
